server:
  port: 8081

spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/bankdb
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update