# testing POST method for branch
POST http://localhost:8081/api/v1/branch
Content-Type: application/json

{
  "branchId" : "b001",
  "branchName": "branch1",
  "branchAddress": "delhi"
}
###
POST http://localhost:8081/api/v1/accounts
Content-Type: application.json

{}
